default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: thirty-days-development

test:
  <<: *default
  database: thirty-days-test

production:
  <<: *default
  database: thirty-days
